version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
      - static_data:/app/static
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start
    depends_on:
      - postgres
    restart: always
    networks:
      - backend_network

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    env_file:
      - .production.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=monino_tools
    #      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5454:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - backend_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - backend_network
    ports:
      - '5050:80'
    depends_on:
      - postgres

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata:
  static_data: